TARGET = iphone:clang:latest:14.0
ARCHS = arm64
LIBRARY_NAME = GhostFramework
GhostFramework_FILES = BypassLoader.mm
GhostFramework_INSTALL_PATH = /usr/local/lib
include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/library.mk
