name: AutoBuild_GhostFramework
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"

      - name: Create Project Files
        run: |
          echo '#import <Foundation/Foundation.h>' > BypassLoader.mm
          echo '#import <dlfcn.h>' >> BypassLoader.mm
          echo '#import <mach-o/dyld.h>' >> BypassLoader.mm
          echo '#define MOD_NAME "UnityAnalyticsCore.dylib"' >> BypassLoader.mm
          echo '#define DELAY_SECONDS 8' >> BypassLoader.mm
          echo 'void cargarModFantasma() {[NSThread sleepForTimeInterval:DELAY_SECONDS]; NSString *path = [[NSBundle mainBundle] bundlePath]; NSString *dylibPath = [path stringByAppendingPathComponent:@MOD_NAME]; dlopen([dylibPath UTF8String], RTLD_NOW);}' >> BypassLoader.mm
          echo '__attribute__((constructor)) static void initialize() {dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{cargarModFantasma();});}' >> BypassLoader.mm
          
          echo 'TARGET = iphone:clang:latest:14.0' > Makefile
          echo 'ARCHS = arm64' >> Makefile
          echo 'include $(THEOS)/makefiles/common.mk' >> Makefile
          echo 'LIBRARY_NAME = GhostFramework' >> Makefile
          echo 'GhostFramework_FILES = BypassLoader.mm' >> Makefile
          echo 'GhostFramework_CFLAGS = -fobjc-arc' >> Makefile
          echo 'include $(THEOS_MAKE_PATH)/library.mk' >> Makefile

      - name: Build Tweak
        run: |
          export THEOS=~/theos
          make package
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GhostFramework_Final
          path: packages/*.deb
